/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/badges`; params?: Router.UnknownInputParams; } | { pathname: `/bedtime`; params?: Router.UnknownInputParams; } | { pathname: `/checkin`; params?: Router.UnknownInputParams; } | { pathname: `/contract`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/records`; params?: Router.UnknownInputParams; } | { pathname: `/rescue`; params?: Router.UnknownInputParams; } | { pathname: `/review`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/shutdown-challenge`; params?: Router.UnknownInputParams; } | { pathname: `/today-review`; params?: Router.UnknownInputParams; } | { pathname: `/tree-hole`; params?: Router.UnknownInputParams; } | { pathname: `/weekly-summary`; params?: Router.UnknownInputParams; } | { pathname: `/sleep-generator`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/badges`; params?: Router.UnknownOutputParams; } | { pathname: `/bedtime`; params?: Router.UnknownOutputParams; } | { pathname: `/checkin`; params?: Router.UnknownOutputParams; } | { pathname: `/contract`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/records`; params?: Router.UnknownOutputParams; } | { pathname: `/rescue`; params?: Router.UnknownOutputParams; } | { pathname: `/review`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/shutdown-challenge`; params?: Router.UnknownOutputParams; } | { pathname: `/today-review`; params?: Router.UnknownOutputParams; } | { pathname: `/tree-hole`; params?: Router.UnknownOutputParams; } | { pathname: `/weekly-summary`; params?: Router.UnknownOutputParams; } | { pathname: `/sleep-generator`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/badges${`?${string}` | `#${string}` | ''}` | `/bedtime${`?${string}` | `#${string}` | ''}` | `/checkin${`?${string}` | `#${string}` | ''}` | `/contract${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/records${`?${string}` | `#${string}` | ''}` | `/rescue${`?${string}` | `#${string}` | ''}` | `/review${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/shutdown-challenge${`?${string}` | `#${string}` | ''}` | `/today-review${`?${string}` | `#${string}` | ''}` | `/tree-hole${`?${string}` | `#${string}` | ''}` | `/weekly-summary${`?${string}` | `#${string}` | ''}` | `/sleep-generator${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/badges`; params?: Router.UnknownInputParams; } | { pathname: `/bedtime`; params?: Router.UnknownInputParams; } | { pathname: `/checkin`; params?: Router.UnknownInputParams; } | { pathname: `/contract`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/records`; params?: Router.UnknownInputParams; } | { pathname: `/rescue`; params?: Router.UnknownInputParams; } | { pathname: `/review`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/shutdown-challenge`; params?: Router.UnknownInputParams; } | { pathname: `/today-review`; params?: Router.UnknownInputParams; } | { pathname: `/tree-hole`; params?: Router.UnknownInputParams; } | { pathname: `/weekly-summary`; params?: Router.UnknownInputParams; } | { pathname: `/sleep-generator`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
